name: 'chicago_crimes_dw'
version: '1.0.0'
config-version: 2

profile: 'chicago_crimes_dw'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  chicago_crimes_dw:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

snapshots:
  chicago_crimes_dw:
    +target_schema: snapshots
    +strategy: check
    +invalidate_hard_deletes: true